roar-web-container:
    image: bclaster/ref-web-image
    ports:
        - "8089:8080"
    links:
        - "roar-db-container:mysql"
roar-db-container:
    image: bclaster/ref-db-image
    ports:
        - "3308:3306"
    environment:
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_DATABASE: registry
        MYSQL_ROOT_PASSWORD: root+1
