apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: roar-web-complete-container
  name: roar-web-complete-container
spec:
  ports:
  - name: "roar"
    port: 8089
    targetPort: 8080
  - name: "mysql"
    port: 3308
    targetPort: 3306
  selector:
    io.kompose.service: roar-web-complete-container
  type: LoadBalancer
status:
  loadBalancer: {}
