apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: roar-web-container
  name: roar-web-container
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: roar-web-container
    spec:
      containers:
      - image: bclaster/ref-web-image
        name: roar-web-container
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
