apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: roar-web-container
  name: roar-web-container
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8080
  selector:
    io.kompose.service: roar-web-container
  type: LoadBalancer
status:
  loadBalancer: {}
