apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: roar-db-container
  name: roar-db-container
spec:
  ports:
  - name: "3308"
    port: 3308
    targetPort: 3306
  selector:
    io.kompose.service: roar-db-container
status:
  loadBalancer: {}
